### ISSUE TITLE
Java warning: "WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs..." 

### ISSUE THREAD

**Issue by julienvollering** [julienvollering/MIAmaxent#1]
When using one of the MIAmaxent functions that relies on the maxent.jar software (e.g. deriveVars, selectDVforEV, selectEV, plotResp), some users have reported the appearance of the following waring message: 
"WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5."

**Comment by julienvollering** [comment]
This is a known java issue, and may be solved by following the procedure suggested by MKorsch on StackOverflow (http://stackoverflow.com/questions/16428098/groovy-shell-warning-could-not-open-create-prefs-root-node):

"1. Go into your Start Menu and type regedit into the search field.
2. Navigate to path HKEY_LOCAL_MACHINE\Software\JavaSoft (Windows 10 seems to now have this here: HKEY_LOCAL_MACHINE\Software\WOW6432Node\JavaSoft)
3. Right click on the JavaSoft folder and click on New -> Key
4. Name the new Key Prefs and everything should work."

**Comment by bbottema** [comment]
Above method solved it for me (executing FindBugs from Maven) under Windows 10 (with HKEY_LOCAL_MACHINE\Software\JavaSoft).

**Comment by avineela** [comment]
Above method solved it for me (executing FindBugs from Maven) under Windows 10 (with HKEY_LOCAL_MACHINE\Software\JavaSoft).

Thanks

**Comment by ooluwadeyi** [comment]
This method worked for me too.
Thanks

**Comment by taigemao** [comment]
@julienvollering Thank you, it works for me. But I actually added new keys to both locations :)

HKEY_LOCAL_MACHINE\Software\JavaSoft 
HKEY_LOCAL_MACHINE\Software\WOW6432Node\JavaSoft

**Comment by amcilwee** [comment]
Thank you. worked for me, but I'm not sure why I get the following error when I run the line:

grasslandDVs <- deriveVars(grasslandPO, transformtype = c("L", "M", "D", "HF", "HR", "T", "B"))

Alpha: returning -Infinity for pi[f]=0.000000+-0.000000, q[f]=0.000091
Error: goodAlpha: returning -Infinity for pi[f]=0.000000+-0.000000, q[f]=0.000091
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input
In addition: Warning message:
running command 'java -mx512m -jar "C:/Users/mcilwea/Documents/R/R-3.4.3/library/MIAmaxent/java/maxent.jar" removeduplicates=FALSE addsamplestobackground=FALSE autofeature=FALSE betamultiplier=0 quadratic=FALSE product=FALSE hinge=FALSE threshold=FALSE outputformat=raw writebackgroundpredictions=TRUE outputgrids=FALSE pictures=FALSE extrapolate=FALSE writemess=FALSE plots=FALSE doclamp=FALSE writeclampgrid=FALSE autorun=TRUE threads=2 visible=FALSE warnings=FALSE maximumbackground=17480 samplesfile="R:/Koala/R/MAXENT/Test/deriveVars/pca1/HR/pca1_HR1/samples.csv" environmentallayers="R:/Koala/R/MAXENT/Test/deriveVars/pca1/HR/pca1_HR1/environlayers.csv" outputdirectory="R:/Koala/R/MAXENT/Test/deriveVars/pca1/HR/pca1_HR1/"' had status 1

**Comment by julienvollering** [comment]
@amcilwee
Are you using maxent.jar version 3.3.3k (in the java folder of the package)?. You can download it from: https://github.com/mrmaxent/Maxent/tree/master/ArchivedReleases/3.3.3k
Currently the link in the system requirements of the package points to an outdated location. My apologies.

MIAmaxent is not yet updated to work with the most recent version of maxent.jar (v3.4.1). We are working on a version of our package that should eliminate these kinds of issues with the java program entirely.

**Comment by amcilwee** [comment]
Thank you. all is working fine.

**Comment by anonym24** [comment]
didn't work for me

I use

```
    private final static String PREF_UPDATE = "prefUpdate";

    private void setPrefUpdateValue(int newValue) {
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        prefs.putInt(PREF_UPDATE, newValue);
    }

    private int getPrefUpdateValue() {
        Preferences prefs = Preferences.userRoot().node(this.getClass().getName());
        int value = prefs.getInt(PREF_UPDATE, 0);
        setPrefUpdateValue(value+1);
        return value;
    }
```

and I get  `WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`

**Comment by bipin79** [comment]
It worked to me too. Thanks julienvollering.

**Comment by justanothercodevan** [comment]
Thx for solution.

**Comment by k-eaton** [comment]
They finally patched this in JDK 8 U202. (This is not the same as the standard JDK. Scroll down the download page to find it below. Apparently Oracle doesn't directly apply the patches to the standard release (U201). You have to download the version that has all the non-security patches in it.) This was finally patched Jan 2019.

**Comment by rooftopcaller** [comment]
very useful , path should with "WOW6432Node" is very important.

**Comment by WinterHuang003** [comment]
部分电脑既找不到HKEY_LOCAL_MACHINE \ Software \ JavaSoft ，
也找不到HKEY_LOCAL_MACHINE \ Software \ WOW6432Node \ JavaSoft。可以在HKEY_LOCAL_MACHINE \ Software \ 找到你对应的应用程序，例如我需要在android studio中使用管理员权限，所以选中Android studio,右键->权限->勾选允许完全控制。问题可完美解决，详见博客https://blog.csdn.net/micotale/article/details/90511141[https://blog.csdn.net/micotale/article/details/90511141](url)

**Comment by WinterHuang003** [comment]
部分电脑既找不到HKEY_LOCAL_MACHINE \ Software \ JavaSoft，
也找不到HKEY_LOCAL_MACHINE \ Software \ WOW6432Node \ JavaSoft。可以在HKEY_LOCAL_MACHINE \ Software \找到你对应的应用程序，例如我需要在android studio中使用管理员权限，所以选中Android studio，右键 - >权限 - >勾选允许完全控制。问题可完美解决，详见博客[https://blog.csdn.net/micotale/article/details/90511141](url)

**Comment by WinterHuang003** [comment]
部分电脑既找不到HKEY_LOCAL_MACHINE \ Software \ JavaSoft，
也找不到HKEY_LOCAL_MACHINE \ Software \ WOW6432Node \ JavaSoft。可以在HKEY_LOCAL_MACHINE \ Software \找到你对应的应用程序，例如我需要在android studio中使用管理员权限，所以选中Android studio，右键 - >权限 - >勾选允许完全控制。问题可完美解决，详见博客https://blog.csdn.net/micotale/article/details/90511141

**Comment by WinterHuang003** [comment]
@julienvollering 部分电脑既找不到HKEY_LOCAL_MACHINE \ Software \ JavaSoft，
也找不到HKEY_LOCAL_MACHINE \ Software \ WOW6432Node \ JavaSoft。可以在HKEY_LOCAL_MACHINE \ Software \找到你对应的应用程序，例如我需要在android studio中使用管理员权限，所以选中Android studio，右键 - >权限 - >勾选允许完全控制。问题可完美解决，详见博客https://blog.csdn.net/micotale/article/details/90511141

**Comment by tony789** [comment]
solved worked on Eclipse 2020 06

**Comment by AymericFerreira** [comment]
Still working in 2020, thank you Julien Vollering

**Comment by tony789** [comment]
I Also thank Julien Vollering

**Comment by Giacomellivinicius** [comment]
Work for mee too! Thanks 👍

**Comment by adelara** [comment]
Thanks !!!
That solved for me too. I'm using Katalon 7.2.1 ... I added the Prefs key to both locations
HKEY_LOCAL_MACHINE\Software\JavaSoft
HKEY_LOCAL_MACHINE\Software\WOW6432Node\JavaSoft

then I modified my Katalon shortcut to always run as administrator.
