### ISSUE TITLE
Error: "'java' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by julienvollering** [julienvollering/MIAmaxent#2]
From Maxent readme:

The problem is either that you don't have Java installed (you need to
install from java.sun.com as above), or Java is not mentioned in your
"path" variable.  To fix the latter problem:

   1.  From the desktop, right click My Computer and click properties.

   2. In the System Properties window, click on the Advanced tab.

   3. In the Advanced section, click the Environment Variables button. 

   4. Finally, in the Environment Variables window, highlight the path
   variable in the Systems Variable section and click edit.  Add the
   directory where the java executable is.  

For example, if you downloaded Java 1.6.0_13, it was probably
installed in C:\Program Files\Java\jdk1.6.0_13, in
which case you will add ";C:\Program Files\Java\jdk1.6.0_13\bin" to
the end of the path variable, like in the following example:

      C:\Program Files;C:\Winnt;C:\Winnt\System32;C:\Program Files\Java\jdk1.6.0_13\bin

**Comment by le-van-tuan** [comment]
Thank you bro, you saved my time 💃

**Comment by Louis95** [comment]
You can test this by restarting you cmd and typing "java --version"

**Comment by njm04** [comment]
Thanks.

**Comment by maukamnm** [comment]
I tried doing that and it still says 'java' is not recognized as an internal or external command,
operable program or batch file.

**Comment by TheKrunch** [comment]
You want to make the path whatever the path is to your java.exe.

**Comment by atulnm2002** [comment]
thank you so much! Wasted like an hour on this finally worked.

**Comment by sonalg49** [comment]
i have tried this and still getting same error

**Comment by jsdmaria** [comment]
Me either

**Comment by Raeeskhosa** [comment]
'java-version' is not recognized as an internal or external command,
operable program or batch file. JDK21/bin path are also set but not is recognized
